In [132]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [133]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [134]:
a.ndim

2

In [135]:
a.shape

(2, 3)

In [136]:
print(a.dtype)

int32


In [137]:
a = np.array([[1,2,3],[4,5,6]], dtype = float)
print(a.dtype)

float64


In [138]:
a.itemsize

8

In [139]:
a.data

In [140]:
a = np.random.random((2,3))
a

array([[0.76118396, 0.50353726, 0.18645729],
       [0.01058622, 0.10976027, 0.24556242]])

In [141]:
a.sum()

1.8170874291983887

In [142]:
a.min()

0.010586218480661325

In [143]:
a.max()

0.7611839626784112

In [144]:
print(type(a))

<class 'numpy.ndarray'>


In [145]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [146]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [147]:
w = np.empty((3,3))
print(w)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [148]:
a

array([[0.76118396, 0.50353726, 0.18645729],
       [0.01058622, 0.10976027, 0.24556242]])

In [149]:
print(a)

[[0.76118396 0.50353726 0.18645729]
 [0.01058622 0.10976027 0.24556242]]


In [150]:
a=np.arange(5,25,4)
print(a)

[ 5  9 13 17 21]


In [151]:
a=np.linspace(5,25,5)
print(a)

[ 5. 10. 15. 20. 25.]


In [152]:
a = np.logspace(5,25,5)
print(a)

[1.e+05 1.e+10 1.e+15 1.e+20 1.e+25]


In [153]:
print(np.sin(a), '\n', np.cos(a), '\n', np.tan(a))

[ 0.0357488  -0.48750603  0.85827279 -0.64525129 -0.3052578 ] 
 [-0.99936081  0.87311962 -0.51319374  0.7639704   0.95226975] 
 [-0.03577166 -0.55834964 -1.67241478 -0.84460246 -0.32055812]


In [154]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [155]:
a = np.random.random((2,2))
print(a)

[[0.15280258 0.4971396 ]
 [0.39635651 0.12264587]]


In [156]:
b = np.exp([10])
print(b)

[22026.46579481]


In [157]:
b = np.sqrt([16])
print(b)

[4.]


In [158]:
a = np.array([5, 10, 15, 20, 25])
b = np.array([0, 1, 2, 3, 0])
c = a - b
print(c) # в методичке была ошибка

[ 5  9 13 17 25]


In [159]:
print(b**2)

[0 1 4 9 0]


In [160]:
print(10 * np.sin(a))

[-9.58924275 -5.44021111  6.5028784   9.12945251 -1.3235175 ]


In [161]:
print(a < 15)

[ True  True False False False]


In [162]:
a = np.array([[1,1], [0,1]])
b = np.array([[2,0],[3,4]])
print(a*b)

[[2 0]
 [0 4]]


In [163]:
print(a@b)

[[5 4]
 [3 4]]


In [164]:
a.dot(b)

array([[5, 4],
       [3, 4]])