In [5]:
import numpy as np
arr1 = np.array([1,2,3,4])
print('arr1 =',arr1)

arr1 = [1 2 3 4]


In [6]:
arr2 = np.array([5,6,7,8], dtype = float)
print('arr2 =',arr2)

arr2 = [5. 6. 7. 8.]


In [7]:
arr2.dtype

dtype('float64')

In [8]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3) # размерность

(3, 3)

In [9]:
import pandas as pd
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [10]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [11]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((3, 3, 3)) # массив размером 3х3х3, заполненный единицами

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [14]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.full((3, 5), 3.14) # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0, 21, 7) # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [17]:
np.linspace(0, 1, 5) # массив из пяти чисел, равномерно распределѐнных в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.random.randint(0, 10, (3, 3)) # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[7, 8, 7],
       [0, 4, 3],
       [1, 2, 3]])

In [19]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_array[5]

5

In [21]:
my_array[-1]

9

In [22]:
my_array[3:6]

array([3, 4, 5])

In [23]:
my_array[1:8:3]

array([1, 4, 7])

In [24]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [25]:
my_array[1][2] # 1 строка 2 столбец

12

In [26]:
students = np.array([[1,135,34,4], [2,160,43,5], [3,163,40,4.3], [4,147,44,5], [5,138,41,4.7]   ])# m * n = 5 * 4
print(students)

[[  1.  135.   34.    4. ]
 [  2.  160.   43.    5. ]
 [  3.  163.   40.    4.3]
 [  4.  147.   44.    5. ]
 [  5.  138.   41.    4.7]]


In [27]:
mean = np.mean(students[:,-1])
mean

4.6

In [28]:
proverka = (4+5+5+4.3+4.7)/5
proverka

4.6

In [29]:
median = np.median(students[:,-1])
median # [4, 4.3, 4.7, 5, 5] --> типо ученик в середине вот такого столбца если выписать их оценки по иерархии

4.7

In [31]:
import numpy as np
corr = np.corrcoef(students[:,1], students[:,2])[0,1]
corr

0.5003147998256952